package resources;
// Generated 9 nov. 2020 0:43:15 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "musica", uniqueConstraints = @UniqueConstraint(columnNames = { "artista_id",
		"name" }))
public class Album implements java.io.Serializable {

	private Integer id;
	private Artista artista;
	private String name;
	private int year;
	private Set<Cancion> cancions = new HashSet<Cancion>(0);

	public Album() {
	}

	public Album(Artista artista, String name, int year) {
		this.artista = artista;
		this.name = name;
		this.year = year;
	}

	public Album(Artista artista, String name, int year, Set<Cancion> cancions) {
		this.artista = artista;
		this.name = name;
		this.year = year;
		this.cancions = cancions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artista_id", nullable = false)
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Cancion> getCancions() {
		return this.cancions;
	}

	public void setCancions(Set<Cancion> cancions) {
		this.cancions = cancions;
	}

}
