package resources;
// Generated 9 nov. 2020 0:43:15 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cancion generated by hbm2java
 */
@Entity
@Table(name = "cancion", catalog = "musica", uniqueConstraints = @UniqueConstraint(columnNames = { "album_id",
		"name" }))
public class Cancion implements java.io.Serializable {

	private Integer id;
	private Album album;
	private String name;
	private double duration;

	public Cancion() {
	}

	public Cancion(Album album, String name, double duration) {
		this.album = album;
		this.name = name;
		this.duration = duration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "album_id", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "duration", nullable = false, precision = 22, scale = 0)
	public double getDuration() {
		return this.duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

}
