package resources;
// Generated 9 nov. 2020 0:43:15 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Discografica generated by hbm2java
 */
@Entity
@Table(name = "discografica", catalog = "musica", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Discografica implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Artista> artistas = new HashSet<Artista>(0);

	public Discografica() {
	}

	public Discografica(String name) {
		this.name = name;
	}

	public Discografica(String name, Set<Artista> artistas) {
		this.name = name;
		this.artistas = artistas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discografica")
	public Set<Artista> getArtistas() {
		return this.artistas;
	}

	public void setArtistas(Set<Artista> artistas) {
		this.artistas = artistas;
	}

}
